# Generated by Django 5.1.6 on 2025-03-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
