# Generated by Django 5.1.6 on 2025-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fecha_agenda_fecha_inicio_agenda_fecha_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=30)),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
